<?php 
    $lang = array(
        'en' => array(
            'icon' => 'EnglandFlag.png',
            'title' => 'Reviews | Apple iPhone 11',
            'bodytitle' => 'Reviews',
            'recommend' => 'recommend',
            'notrecommend' => 'does not recommend',
            'formtitle' => 'Write a review',
            'name' => 'Name and surname:',
            'gender' => 'Gender:',
            'man' => 'Male',
            'woman' => 'Female',
            'rating' => 'Recommendation:',
            'formrecommend' => 'Recommend',
            'formnotrecommend' => 'Does not recommend',
            'message' => 'Write a review here:',
        ),
        'sk' => array(
            'icon' => 'SlovakiaFlag.png',
            'title' => 'Recenzie | Apple iPhone 11',
            'bodytitle' => 'Recenzie',
            'recommend' => 'doporučuje',
            'notrecommend' => 'nedoporučuje',
            'formtitle' => 'Napíšte recenziu',
            'name' => 'Meno a priezvisko:',
            'gender' => 'Pohlavie:',
            'man' => 'Muž',
            'woman' => 'Žena',
            'rating' => 'Hodnotenie:',
            'formrecommend' => 'Doporučujem',
            'formnotrecommend' => 'Nedoporučujem',
            'message' => 'Sem napíšte recenziu:',
        ),
    );
?>